POST {{host}}/applications/{{application_id}}/callbacks
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Product Callback 9002",
    "httpMethod": "POST",
    "url": "http://192.168.1.101:9002/wh/product"
}

> extract-callback-id.js

###

GET {{host}}/applications/60361fc7d7582d3e57824b5a/callbacks
Accept: application/json
Authorization: Bearer {{token}}

###

GET {{host}}/applications/{{application_id}}/callbacks/{{callback_id}}
Accept: application/json
Authorization: Bearer {{token}}

###

DELETE {{host}}/applications/{{application_id}}/callbacks/{{callback_id}}
Accept: text/plain
Accept: application/json
Authorization: Bearer {{token}}

###

PUT {{host}}/applications/{{application_id}}/callbacks/{{callback_id}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Product Callback 9004",
    "httpMethod": "POST",
    "url": "http://192.168.1.101:9004/wh/weather",
    "security": {
        "secret": {
            "keyId": "my-key-id",
            "secret": "MY SECRET"
        }
    }
}

###

