POST http://localhost:9005/publish
Accept: text/plain, application/json
Content-Type: application/json
wh-topic: DevicePositionUpdate
#wh-topic: OrderChange
#wh-topic: CancelledOrder
#wh-topic: CreateNewOrder
#wh-topic: OrderDelivered
Authorization: Bearer {{token}}
#wh-authorized-subscriber: Hookie Solutions

< data.json

###

POST http://localhost:9005/publish/queue
Accept: text/plain, application/json
Content-Type: application/json
#wh-topic: createdPet
#wh-topic: updatedSong
wh-topic: createdOrder
#wh-topic: createdSong
#wh-topic: createdAlbum
#h-count: 10
#wh-trace-id: b7823282-fef8-4af0-b162-e2f754aec9d4
#wh-trace-id: 6
Authorization: Bearer {{token}}
#wh-authorized-subscriber: Hookie Solutions

< data.json

###

POST http://localhost:8080/consumer/event
Accept: text/plain, application/json
Content-Type: application/json
wh-topic: DevicePositionUpdate
wh-trace-id: 1
Authorization: Bearer {{token}}

< data.json

###

POST http://localhost:9005/publish
Accept: text/plain, application/json
Content-Type: application/json
wh-topic: NewOrder
Authorization: Bearer {{token}}

< data.json

###

