POST http://{{host}}/async/read
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

< wh_group_yaml.json

###

POST http://{{host}}/async/read
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

< wh_group.json

###

POST http://{{host}}/async/read
Accept: application/json
Content-Type: text/yaml
Authorization: Bearer {{token}}

< asyncapi.yml

###

POST http://{{host}}/async/read
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

< asyncapi.json

###

GET http://{{host}}/publisher
Authorization: Bearer {{token}}

