GET {{host}}/traffic/trace
Accept: application/json
Authorization: Bearer {{token}}

###

GET {{host}}/traffic/trace?page=1&size=2&sort=statusUpdate1.status,DESC
Accept: application/json
Authorization: Bearer {{token}}

###

GET {{host}}/traffic/trace?to=2021-03-19T00:21:47.577Z
Accept: application/json
Authorization: Bearer {{token}}

###

GET {{host}}/traffic/trace?traceId=5c7&application=My Order Application 1&entity=Hookie Solutions&topic=Order
Accept: application/json
Authorization: Bearer {{token}}

###

GET {{host}}/traffic/span?traceId=5c7&application=My&entity=Hookie&callback=900
Accept: application/json
Authorization: Bearer {{token}}

###

GET {{host}}/traffic/span?page=0&size=2&sort=latestResult.retryNo,DESC
Accept: application/json
Authorization: Bearer {{token}}

###


GET {{host}}/traffic/span?page=0&size=2&sort=subscription.topic
Accept: application/json
Authorization: Bearer {{token}}

###

GET {{host}}/traffic/trace/5f433c30-677e-40fc-baf3-0a3270db53ed/request
Accept: application/json
Authorization: Bearer {{token}}

###


GET {{host}}/traffic/trace/dc7d3837-bee6-4eca-bd29-22f620a96755/request
Accept: application/json
Authorization: Bearer {{token}}

###

