POST {{host}}/admin/consumergroups
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Webhookie Consumer Group 1",
    "description": "Suppliers Consumer Group",
    "iamGroupName": "Webhookie_Consumer1"
}

> extract-consumer-id.js

###

PUT {{host}}/admin/consumergroups/601e5f00f88a4521d236e82c
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Consumer Group 11",
    "description": "Auth0 Consumer Group 11",
    "iamGroupName": "Consumer Group 11"
}

###

GET {{host}}/admin/consumergroups
Accept: application/json
Authorization: Bearer {{token}}

###

GET {{host}}/admin/consumergroups/{{consumer_group_id}}
Accept: application/json
Authorization: Bearer {{token}}

###

DELETE {{host}}/admin/consumergroups/601e5f1cf88a4521d236e82e
Accept: text/plain
Accept: application/json
Authorization: Bearer {{token}}

###
