POST http://localhost:9010/callback
Content-Type: application/json
#Authorization: Bearer eyJraWQiOiJfTE5FdnJRR01aMjJrMW9Nc1N3OUxtVE1CZVlNalpLNXVVMWVMVG9udFpFIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULnI0Tm9BZ0g0WmRFcU9LMjVQdzlTRUt3aUdpNUpuZXVIQzBRNFMxTTZNbzgiLCJpc3MiOiJodHRwczovL2Rldi0xODA3MDE5Lm9rdGEuY29tL29hdXRoMi9kZWZhdWx0IiwiYXVkIjoiYXBpOi8vZGVmYXVsdCIsImlhdCI6MTY1MDc4MzM1NiwiZXhwIjoxNjUwNzgzNjU2LCJjaWQiOiIwb2EydzV1cjlwRm55R1czVzVkNyIsInNjcCI6WyJtb2RfY3VzdG9tIl0sInN1YiI6IjBvYTJ3NXVyOXBGbnlHVzNXNWQ3In0.gRv7nbPLI3fn2IAvnbtJOstAlJiCuucEPPIwYP80CcPwU63II3KaYzYc4GAftBaIQHkhbeF1X9ONfKWAtuMnHSNgZQxIuQnNrTIAwAY5Af9BAX-P1j6l4E2UDY3PLpYa0JFXRrDLBVeHBS1jaKOXwl170D_rM6wSHb1aBS6tQT8TsrYus42L9LqDzgPDNUatPmpCmFhiltBpQAem0JYT5Enu1pogv_pOnZkPsknM1CPLwkGaoGoqq5xKCa24ggirZcjuwZAK837lc1zOmRVQE4FBVVTjJisu-cEtkUoR5cKo5CWYttTn94grA9rL6rlVU-cmv5H7goOFQuZ6_acgfA

{
  "message": "Hi!"
}

###

POST http://localhost:9010/callback?hmac=true
Content-Type: application/json
#Authorization: Bearer eyJraWQiOiJfTE5FdnJRR01aMjJrMW9Nc1N3OUxtVE1CZVlNalpLNXVVMWVMVG9udFpFIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULnI0Tm9BZ0g0WmRFcU9LMjVQdzlTRUt3aUdpNUpuZXVIQzBRNFMxTTZNbzgiLCJpc3MiOiJodHRwczovL2Rldi0xODA3MDE5Lm9rdGEuY29tL29hdXRoMi9kZWZhdWx0IiwiYXVkIjoiYXBpOi8vZGVmYXVsdCIsImlhdCI6MTY1MDc4MzM1NiwiZXhwIjoxNjUwNzgzNjU2LCJjaWQiOiIwb2EydzV1cjlwRm55R1czVzVkNyIsInNjcCI6WyJtb2RfY3VzdG9tIl0sInN1YiI6IjBvYTJ3NXVyOXBGbnlHVzNXNWQ3In0.gRv7nbPLI3fn2IAvnbtJOstAlJiCuucEPPIwYP80CcPwU63II3KaYzYc4GAftBaIQHkhbeF1X9ONfKWAtuMnHSNgZQxIuQnNrTIAwAY5Af9BAX-P1j6l4E2UDY3PLpYa0JFXRrDLBVeHBS1jaKOXwl170D_rM6wSHb1aBS6tQT8TsrYus42L9LqDzgPDNUatPmpCmFhiltBpQAem0JYT5Enu1pogv_pOnZkPsknM1CPLwkGaoGoqq5xKCa24ggirZcjuwZAK837lc1zOmRVQE4FBVVTjJisu-cEtkUoR5cKo5CWYttTn94grA9rL6rlVU-cmv5H7goOFQuZ6_acgfA

{
  "message": "Hi!"
}

###

POST http://localhost:9010/oauth2/test
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "say": "hi"
}
